.TH SITPLUS 1 "Last change: August 2011" Linux "User's Manuals"
.SH NAME
sitplus \- Free software framework for ludic-therapeutic activities
.SH SYNOPSIS
.B sitplus [-h] [--verbose]
.SH DESCRIPTION
.B Sitplus
is a free software (GNU GPL) framework whose main goal is to provide ludic-therapeutic activities for people with disabilities. It offers new forms of interaction based on computer vision, voice and other peripherals to produce a result in the form of image and sound. Inspired by the cause and effect applications, SITPLUS provides a tool for continuous and remote interaction, attainable to the majority of people with cognitive, sensory and physical disabilities.
.SH OPTIONS
.IP "-h, --help"
Show a help message
.IP "--verbose"
Generate verbose log messages
.SH AUTHOR
Cesar Mauri Loba <cesar@crea-si.com>
